// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "stock-bot/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// PositionRepository is an autogenerated mock type for the PositionRepository type
type PositionRepository struct {
	mock.Mock
}

// DeletePosition provides a mock function with given fields: ctx, symbol
func (_m *PositionRepository) DeletePosition(ctx context.Context, symbol string) error {
	ret := _m.Called(ctx, symbol)

	if len(ret) == 0 {
		panic("no return value specified for DeletePosition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, symbol)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *PositionRepository) FindAll(ctx context.Context) ([]*model.Position, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*model.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Position, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Position); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Position)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBySymbol provides a mock function with given fields: ctx, symbol
func (_m *PositionRepository) FindBySymbol(ctx context.Context, symbol string) (*model.Position, error) {
	ret := _m.Called(ctx, symbol)

	if len(ret) == 0 {
		panic("no return value specified for FindBySymbol")
	}

	var r0 *model.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Position, error)); ok {
		return rf(ctx, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Position); ok {
		r0 = rf(ctx, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Position)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, position
func (_m *PositionRepository) Save(ctx context.Context, position *model.Position) error {
	ret := _m.Called(ctx, position)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Position) error); ok {
		r0 = rf(ctx, position)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateHighestPrice provides a mock function with given fields: ctx, symbol, price
func (_m *PositionRepository) UpdateHighestPrice(ctx context.Context, symbol string, price float64) error {
	ret := _m.Called(ctx, symbol, price)

	if len(ret) == 0 {
		panic("no return value specified for UpdateHighestPrice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) error); ok {
		r0 = rf(ctx, symbol, price)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertPositionByExecution provides a mock function with given fields: ctx, execution
func (_m *PositionRepository) UpsertPositionByExecution(ctx context.Context, execution *model.Execution) error {
	ret := _m.Called(ctx, execution)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPositionByExecution")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Execution) error); ok {
		r0 = rf(ctx, execution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPositionRepository creates a new instance of PositionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPositionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PositionRepository {
	mock := &PositionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
