// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	client "stock-bot/internal/infrastructure/client"

	mock "github.com/stretchr/testify/mock"

	request "stock-bot/internal/infrastructure/client/dto/price/request"

	response "stock-bot/internal/infrastructure/client/dto/price/response"
)

// PriceInfoClient is an autogenerated mock type for the PriceInfoClient type
type PriceInfoClient struct {
	mock.Mock
}

// GetPriceInfo provides a mock function with given fields: ctx, session, req
func (_m *PriceInfoClient) GetPriceInfo(ctx context.Context, session *client.Session, req request.ReqGetPriceInfo) (*response.ResGetPriceInfo, error) {
	ret := _m.Called(ctx, session, req)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceInfo")
	}

	var r0 *response.ResGetPriceInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.Session, request.ReqGetPriceInfo) (*response.ResGetPriceInfo, error)); ok {
		return rf(ctx, session, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.Session, request.ReqGetPriceInfo) *response.ResGetPriceInfo); ok {
		r0 = rf(ctx, session, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ResGetPriceInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.Session, request.ReqGetPriceInfo) error); ok {
		r1 = rf(ctx, session, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPriceInfoHistory provides a mock function with given fields: ctx, session, req
func (_m *PriceInfoClient) GetPriceInfoHistory(ctx context.Context, session *client.Session, req request.ReqGetPriceInfoHistory) (*response.ResGetPriceInfoHistory, error) {
	ret := _m.Called(ctx, session, req)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceInfoHistory")
	}

	var r0 *response.ResGetPriceInfoHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.Session, request.ReqGetPriceInfoHistory) (*response.ResGetPriceInfoHistory, error)); ok {
		return rf(ctx, session, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.Session, request.ReqGetPriceInfoHistory) *response.ResGetPriceInfoHistory); ok {
		r0 = rf(ctx, session, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ResGetPriceInfoHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.Session, request.ReqGetPriceInfoHistory) error); ok {
		r1 = rf(ctx, session, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPriceInfoClient creates a new instance of PriceInfoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceInfoClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceInfoClient {
	mock := &PriceInfoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
